---
title: "bottle test"
author: "CB Wall"
date: "2024-01-18"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
---

```{r setup chunk, setup, include = FALSE, cache=FALSE, message=FALSE, warning=FALSE, collapse=TRUE}
if (!require('knitr')) install.packages('knitr'); library('knitr')
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.align='center')


######### load in packages and set global settings

# load packages
if (!require("pacman")) install.packages("pacman") # for rapid install if not in library

# use pacman to load all the packages you are missing!
pacman::p_load('knitr', 'lme4', 'lmerTest', 'tidyverse', 'magrittr', 'effects', 'plyr', 'dplyr', 'plotrix', 'car',"gridExtra", "cowplot", "tools", "mgcv", "gratia", "MASS", "stats", "tidymv", "sjstats", "coin", "emmeans")


Fig.formatting<-(theme_classic()) +
  theme(text=element_text(size=10),
        axis.line=element_blank(),
        legend.text.align = 0,
        legend.text=element_text(size=10),
        #legend.title = element_blank(),
        panel.border = element_rect(fill=NA, colour = "black", size=1),
        aspect.ratio=1, 
        axis.ticks.length=unit(0.25, "cm"),
        axis.text.y=element_text(
          margin=unit(c(0.5, 0.5, 0.5, 0.5), "cm"), colour="black", size=10), 
        axis.text.x=element_text(
          margin=unit(c(0.5, 0.5, 0.5, 0.5), "cm"), colour="black", size=8)) +
  theme(legend.key.size = unit(0.4, "cm")) +
  theme(aspect.ratio=1.3) +
  theme(panel.spacing=unit(c(0, 0, 0, 0), "cm"))

```


### bottle test
```{r bottle incubation tests}
bottles<-read.csv("data/bottle.type.test.data.csv")
str(bottles)

make.fac<-c("Bottle.ID", "material", "sealed.flowthrough", "material.flow.inter", "light.exposure")
bottles[make.fac] <- lapply(bottles[make.fac], factor) # make all these factors

bottles$daph.dens..indiv.L<-ifelse(bottles$material=="glass", bottles$Daphnia.end.count.7d/0.470,
                           bottles$Daphnia.end.count.7d/0.900)

bottles$daph.perc.change<-((bottles$Daphnia.end.count.7d - 10) / 10)*100

# material: glass vs. plastic
ggplot(bottles, aes(x=material, y=Daphnia.end.count.7d, fill=material)) + 
  geom_boxplot(alpha=0.2) +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6)


# flow: glass vs. plastic
ggplot(bottles, aes(x=sealed.flowthrough, y=Daphnia.end.count.7d, fill=sealed.flowthrough)) + 
  geom_boxplot(alpha=0.2) +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6)


# light: dark vs. bright
ggplot(bottles, aes(x=light.exposure, y=Daphnia.end.count.7d, fill=light.exposure)) + 
  geom_boxplot(alpha=0.2) +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6)

############
########
###

# orthogonal: dark vs. bright with material and flow
total.Daph<-ggplot(bottles, aes(x=light.exposure, y=Daphnia.end.count.7d, fill=material.flow.inter)) + 
  geom_boxplot(alpha=0.5) +
  ggtitle("Post-7d incubation") +
  ylab("Total Daphnia") +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_fill_manual(values=c("dodgerblue", "lightblue", "coral", "pink"))


# orthog Daph PER Liter: dark vs. bright with material and flow
daph.density<-ggplot(bottles, aes(x=light.exposure, y=daph.dens..indiv.L, fill=material.flow.inter)) + 
  geom_boxplot(alpha=0.5) +
  ggtitle("Post-7d incubation") +
  ylab("Daphnia/L") +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_fill_manual(values=c("dodgerblue", "lightblue", "coral", "pink"))


# orthog Daph PERCENT change: dark vs. bright with material and flow
daph.percent<-ggplot(bottles, aes(x=light.exposure, y=daph.perc.change, fill=material.flow.inter)) + 
  geom_boxplot(alpha=0.5) +
  ggtitle("Post-7d incubation") +
  ylab("Daphnia percent change") +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_fill_manual(values=c("dodgerblue", "lightblue", "coral", "pink"))


# change in O2
DO.change<-ggplot(bottles, aes(x=light.exposure, y=DO.bottle..perc..POOLED, fill=material.flow.inter)) + 
  geom_boxplot(alpha=0.5) +
  ggtitle("DO change from tank") +
  ylab("DO %") +
  coord_cartesian(ylim=c(20, 100)) +
  geom_hline(yintercept=78.4, linetype="longdash", color = "gray") + # tank DO
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6, size=4) +
  scale_fill_manual(values=c("dodgerblue", "lightblue", "coral", "pink"))

######## plot export
bottle.plots<-plot_grid(
  total.Daph+ theme(legend.position = "none") + ggtitle("Post-7d incubation"), 
  daph.density+ ggtitle(""),
  daph.percent+ theme(legend.position = "none") + ggtitle(""),
  DO.change +ggtitle(""),
  rel_widths = c(8,11,8,11), ncol=2)

ggsave("figures/bottle.testdata.pdf", height=9, width=9)

```
